#!/usr/bin/php
<?PHP

//$GEOIPURL="https://dl.miyuru.lk/geoip/maxmind/city/maxmind4.dat.gz";
$GEOIPURL="https://dl.miyuru.lk/geoip/dbip/city/dbip4.dat.gz";
// Change the next two lines to suit
$home = __DIR__; // path to fail2sql directory

require($home."/../dbinfo.php");

$geoCityFile=$home."/GeoLiteCity.dat";

$action = $_SERVER["argv"][1];

if ($action == "-l") {
  $query = "SELECT *, COUNT(IP) FROM `fail2ban` GROUP BY IP limit 200";
  $result = mysqli_query($link,$query) or die('Query failed: ' . mysqli_error($link));
  while ($row = mysqli_fetch_array($result, MYSQLI_NUM)) {
    echo $row[1]."(".$row[3]."/".$row[2]."): ".$row[4]." | Count: ".$row[5]." | Geo: ".$row[9]."\n";
  }
  mysqli_close($link);
  exit;
}else if ($action == "-f") {
  $query = "UPDATE `fail2ban` set `ban` = 0";
  $result = mysqli_query($link,$query) or die('Query failed: ' . mysqli_error($link));
  echo "Resetting database\n";
  exit;
}else if ($action == "-u") {
  if(!file_exists($geoCityFile) || time()-filemtime($geoCityFile) >= 60 * 60 * 24 ){
  	exec("wget -O - \"$GEOIPURL\" |zcat - > $geoCityFile");
  }else{
        echo "File is too recent, not updating it. Remove ".$geoCityFile." if you want to force refresh\n";
  } 
  exit;
}else if ($action == "-h") {
  print_help();
}



#not working anymore to due multiple ports ban => ports is now varchar
#if (!preg_match('/^\d{1,5}$/', $ports)) {
#  $ports = getservbyname($_SERVER["argv"][4], $protocol);
#}

if($action == '-t'){
  $ip = addslashes(trim($_SERVER["argv"][2]));
  if (!$ip) {
    print_help();
  }
}else{
  $name = addslashes(trim($_SERVER["argv"][2]));
  $protocol = addslashes(trim($_SERVER["argv"][3]));
  $ports = addslashes(trim($_SERVER["argv"][4]));
  $ip = addslashes(trim($_SERVER["argv"][5]));

  if (!$name || !$ip || !$protocol || !$ports) {
    print_help();
  }
}



if ($action == "-d") {
  $query = "UPDATE `fail2ban` set `ban`=0 where `ip`='".$ip."' and `name`='".$name."'";
  $result = mysqli_query($link,$query) or die('Query failed: ' . mysqli_error($link));
  echo "Unban $name $ip \n";
  exit;
}





include($home."/geoipcity.inc");
include($home."/geoipregionvars.php");


$geodb = geoip_open($geoCityFile,GEOIP_STANDARD) or die ('Failed to open Geo Database');
$geoip = geoip_record_by_addr($geodb,$ip);
if($action == '-t'){
  print_r($geoip);
}else{
  if ($geoip) {
    $query = "INSERT INTO `fail2ban` values (NULL, '".$name."', '".$protocol."', '".$ports."', '".$ip."', '".$geoip->longitude."', '".$geoip->latitude."', '".$geoip->country_code."', '".$geoip->country_code3."', '".$geoip->city."', '".$geoip->country_name."', NOW(), 1)";
    echo "Inserting $ip into database with geo info\n$query";
  }else {
    $query = "INSERT INTO `fail2ban` values ('', '".$name."', '".$protocol."', '".$ports."', '".$ip."', '', '', '', '', '', '', NOW(), 1)";
    echo "Inserting $ip into database without geo info\n";
  }
  $result = mysqli_query($link,$query) or die('Query failed: ' . mysqli_error($link));
}


mysqli_close($link);

function print_help() {
  echo "Fail2SQL v1.0 by Jordan Tomkinson <jordan@moodle.com> Updated by Amaury BOLLER <banhammer#boller.co>\n";
  echo "Usage: ".$_SERVER["argv"][0]." [-h|-l|-u|-b|-d]\n";
  echo "\t -h: This page\n";
  echo "\t -l: List entries in the database (max 50 showed)\n";
  echo "\t -f: Flush the database and start fresh (just set flag ban to 0 for all entries, does not remove any IP)\n";
  echo "\t -u: Update GeoIP database (Use legacy update from dl.miyuru.lk)\n";
  echo "\t -b  <name> <protocol> <ports> <ip> : to ban an IP\n";
  echo "\t -d <name> <ip>: to flag ip as unban\n\n";
  echo "To call this script from Fail2Ban append the following line to 'actionban =' and restart fail2ban\n";
  echo "/path/to/fail2sql -b <name> <protocol> <port> <ip>\n";
  echo "Example for /etc/fail2ban/action.d/iptables.conf\n";
  echo "actionban = iptables -I fail2ban-<name> 1 -s <ip> -j DROP\n";
  echo "            /usr/local/fail2sql/fail2sql -b <name> <protocol> <port> <ip>\n";
  exit;
}

?>
